name: Push to ECR Inkomoko

on:

  push:
    branches: [ inkomoko ]

jobs:

  deploy:

    name: Deploy image to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: kamiazya/setup-graphviz@v1


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_inkomoko }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_inkomoko }}
          aws-region: eu-central-1

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fineract
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
